name: Build and Release AMAI_GUI.exe

on:
  push:
    tags:
      - 'v*' # 触发标签如 v1.0, v2.1 等，表示发布版本

jobs:
  build:
    name: Build Windows EXE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MinGW for Windows cross-compilation
      uses: egor-tensin/setup-mingw@v3
      with:
        architecture: x86_64

    - name: Compile AMAI_GUI.exe (GUI, no console)
      run: |
        mkdir -p dist
        x86_64-w64-mingw32-gcc \
          -mwindows \
          -municode \
          -O2 \
          -Wall \
          -Wextra \
          -finput-charset=UTF-8 \
          -fexec-charset=CP936 \
          src/main.c \
          -o dist/AMAI_GUI.exe \
          -lcomctl32
        echo " Compiled: dist/AMAI_GUI.exe"

    - name: Create ZIP package
      run: |
        cd dist && zip -r ../AMAI_GUI_Windows.zip *

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v4
      with:
        path: AMAI_GUI_Windows.zip
        name: AMAI_GUI_Windows

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: AMAI_GUI_Windows
        path: AMAI_GUI_Windows.zip
