name: Build Windows Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install required tools
      run: |
        choco install -y upx

    - name: Create build directory
      run: mkdir build

    - name: Build application
      run: |
        cl /O1 /Os /GS- /MT /FeAMAI-Installer.exe main.c user32.lib gdi32.lib comctl32.lib shell32.lib ole32.lib comdlg32.lib /link /ENTRY:WinMainCRTStartup /SUBSYSTEM:WINDOWS /MACHINE:X64  
        if ($LASTEXITCODE -ne 0) {  
            Write-Host "Compilation failed!"  
            exit 1  
        }  

    - name: Debug directory
      run: |
        Write-Host "当前目录内容:"
        Get-ChildItem
        Write-Host "build目录内容:"
        Get-ChildItem -Path build

    - name: Compress with UPX
      run: |
        cd build
        upx --best --lzma AMAI-Installer.exe
        # 检查压缩后的文件大小
        dir AMAI-Installer.exe

    - name: Prepare artifacts
      run: |
        mkdir dist
        copy AMAI-Installer.exe dist
  

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AMAI-Installer
        path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: AMAI-Installer
        path: dist

