name: Build Windows Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install required tools
      run: |
        choco install -y make
        choco install -y upx

    - name: Build application
      run: |
        cl /O1 /Os /GS- /MT /FeAMAI-Installer.exe src/main.c user32.lib gdi32.lib comctl32.lib shell32.lib
        upx --best --lzma AMAI-Installer.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AMAI-Installer
        path: |
          AMAI-Installer.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: AMAI-Installer
        path: dist

    - name: Create release
      uses: softprops/action-gh-release@v4
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        files: |
          dist/AMAI-Installer.exe
